# 1. Unbind the default Ctrl+b leader key
unbind C-b

# 2. Set the new leader key to Ctrl+Space
set -g prefix C-Space

# 3. Ensure you can send Ctrl+Space to other apps by pressing it twice
bind C-Space send-prefix

# Split vertical (lado a lado) usando |
bind | split-window -h -c "#{pane_current_path}"

# Split horizontal (cima/baixo) usando \\
bind \\ split-window -v -c "#{pane_current_path}"

# New and select windows using Leader (C-Space) then Number
bind-key 0 if-shell "tmux select-window -t :0" "" "new-window -t :0"
bind-key 1 if-shell "tmux select-window -t :1" "" "new-window -t :1"
bind-key 2 if-shell "tmux select-window -t :2" "" "new-window -t :2"
bind-key 3 if-shell "tmux select-window -t :3" "" "new-window -t :3"
bind-key 4 if-shell "tmux select-window -t :4" "" "new-window -t :4"
bind-key 5 if-shell "tmux select-window -t :5" "" "new-window -t :5"
bind-key 6 if-shell "tmux select-window -t :6" "" "new-window -t :6"
bind-key 7 if-shell "tmux select-window -t :7" "" "new-window -t :7"
bind-key 8 if-shell "tmux select-window -t :8" "" "new-window -t :8"
bind-key 9 if-shell "tmux select-window -t :9" "" "new-window -t :9"

# Close the current window without confirmation prompt
bind-key c run-shell "tmux kill-window"

# Kill session
bind-key q run-shell "tmux kill-session"

# Unbind dos atalhos padrões antigos
unbind '"'
unbind %
unbind -

set -g @plugin 'tmux-plugins/tpm' 
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum' # Restaura automaticamente ao abrir o tmux 
set -g @continuum-restore 'on' # Salva o estado automaticamente acada 15 min 
set -g @continuum-save-interval '15' 
set -g @resurrect-dir '~/.tmux/resurrect'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

