# 1. Unbind the default Ctrl+b leader key
unbind C-b

# 2. Set the new leader key to Ctrl+Space
set -g prefix C-Space

# 3. Ensure you can send Ctrl+Space to other apps by pressing it twice
bind C-Space send-prefix

# Split vertical (lado a lado) usando |
bind | split-window -h -c "#{pane_current_path}"

# Split horizontal (cima/baixo) usando \
bind \\ split-window -v -c "#{pane_current_path}"

# Unbind dos atalhos padrões antigos
unbind '"'
unbind %
unbind -

set -g @plugin 'tmux-plugins/tpm' 
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum' # Restaura automaticamente ao abrir o tmux 
set -g @continuum-restore 'on' # Salva o estado automaticamente acada 15 min 
set -g @continuum-save-interval '15' 
set -g @resurrect-dir '~/.tmux/resurrect'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

